# Image parameters
IMAGE_SIZE: [224, 224]

# Model parameters
WEIGHTS: imagenet
INCLUDE_TOP: false
CLASSES: 4

# Training parameters - OPTIMIZED FOR 95%+ ACCURACY
LEARNING_RATE: 0.0001
BATCH_SIZE: 16
EPOCHS: 50
AUGMENTATION: true